server:
  port: 0

spring:
  devtools:
    restart:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: 172.31.20.187:9092

eureka:
  client:
    service-url:
      defaultZone: http://admin:production-strong-password@172.31.26.79:8010/eureka

logging:
  file:
    name: /api-logs/notification-service.log