version: '3'
services:

  user-db:
    container_name: users
    image: postgres:16.2
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5442:5432"

  product-db:
    container_name: products
    image: postgres:16.2
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5443:5432"

  order-db:
    container_name: orders
    image: postgres:16.2
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5444:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Internal port for Docker network
      - "29092:9092" # External port for host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
