server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        #user registration
        - id: user-service-auth-register
          uri: lb://user-service #app name after lb://
          predicates:
            - Path=/user-service/auth/register
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        #user/admin login
        - id: user-service-auth-login
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/authenticate
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        #user crud
#        - id: user-service-user-crud
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/user
#            - Method=GET,POST,PUT,DELETE
#            - Header=Authorization, Bearer (.*) #request must have bearer token in its header
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /${segment}
#            - AuthorizationHeaderFilter #NEW
#        #admin crud
#        - id: user-service-admin-crud
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/admin
#            - Method=GET,POST,PUT,DELETE
#            - Header=Authorization, Bearer (.*)
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /${segment}
#            - AuthorizationHeaderFilter #NEW
              #admin crud
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/user-service/admin/**
            - Method=GET,POST,PUT,DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_ADMIN
        - id: user-service-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/user/**
            - Method=GET,UPDATE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
            - AuthorizationHeaderFilter=ROLE_USER ROLE_ADMIN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

token:
  secret: 9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3b9a0e7c


