server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #user
        - id: user-service-register
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/**
            - Method=POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        - id: auth-service-authenticate
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/auth/authenticate
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: user-service-get-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        #product
        - id: product-service-create
          uri: lb://product-service
          predicates:
            - Path=/product-service/product/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
        #stock
        - id: product-service-create-stock
          uri: lb://product-service
          predicates:
            - Path=/product-service/stock/**
            - Method=POST,PUT,GET,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
        #order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
        #actuator
        - id: auth-service-actuator
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: user-service-actuator
          uri: lb://user-service
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        - id: product-service-actuator
          uri: lb://product-service
          predicates:
            - Path=/product-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
        - id: order-service-actuator
          uri: lb://order-service
          predicates:
            - Path=/order-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}
        - id: notification-service-actuator
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/actuator/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/notification-service/(?<segment>.*), /${segment}


eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8010/eureka

token:
  secret: 9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3b9a0e7c

logging:
  file:
    name: /Users/artemayvazyan/Desktop/tierserviceapp/backend/api-gateway/api-gateway.log

management:
  endpoint:
    gateway:
      enabled: true #listing all routes that are configured here
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings #to expose endpoint through http