server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #user
        - id: user-service-register
          uri: lb://user-service #app name after lb://
          predicates:
            - Path=/user-service/users/register
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
        - id: auth-service-authenticate
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/auth/authenticate
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /${segment}
        - id: user-service-get-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /${segment}
          #product
        - id: product-service-create
          uri: lb://product-service
          predicates:
            - Path=/product-service/product/**
            - Method=POST,GET,PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
        #stock
        - id: product-service-create-stock
          uri: lb://product-service
          predicates:
            - Path=/product-service/stock
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /${segment}
        #order
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8010/eureka

token:
  secret: 9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3b9a0e7c

logging:
  file:
    name: /Users/artemayvazyan/Desktop/tierserviceapp/backend/api-gateway/api-gateway.log

