spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.fel.cvut.cz/aivazart/tier-service-configuration
          username: aivazart
          password: glpat-xcYTiV3nP4vZXpsQB75j #Access Token
          clone-on-start: true
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8012

management:
  endpoints:
    web:
      exposure:
        include: busrefresh



