services:
  db:
    container_name: users
    image: postgres:16.2
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"